### ISSUE TITLE
Back slashes not escaped properly in generated CSS

### ISSUE THREAD

**Issue by jeremyc2** [jeremyc2/tailwind-lit-rollup-plugin#1]
CSS generated from tailwind needs to have backslashes escaped, or else they get ignored by the browser. 

Example:

```css
.hover\:scale-90:hover {
    --tw-scale-x: .9;
    --tw-scale-y: .9;
    transform: translate(var(--tw-translate-x), var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y))
}
```
